$(document).on("click",".shop",function(){
	location.href="details.html";
})
$(document).on("click",".shopcar",function(){
	location.href="shopcar.html";
})
$(document).on("click",".hockshop",function(){
	location.href="hockshop.html";
})
$(document).on("click",".menCenter",function(){
	location.href="menCenter.html";
})